Default: &defaults
  database: yesodQuiz.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: yesodQuiz_test.sqlite3
  <<: *defaults

Staging:
  database: yesodQuiz_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: yesodQuiz_production.sqlite3
  poolsize: 100
  <<: *defaults
